/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Create-Plant-Type": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Delete-Plant-Type": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Get-Plant-Type": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Get-Plant-Type-List": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Update-Plant-Type": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}