/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Dispatcher": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "SLACK_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SLACK_SIGNING_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Slack": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}